
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:db11g
    username: QLTD
    password: Viethoang_99
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:  cutetiger98.java@gmail.com
    password: vkqingjddopedqbw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
