spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: recruitment_management_itsol
    password: pass
    driver-class-name: oracle.jdbc.driver.OracleDriver
  data:
    rest:
      base-path: api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: cutetiger98.java@gmail.com
    password: vkqingjddopedqbw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8001

application:
  active-account:
    active-url: "http://localhost:8080/active/"

